module.exports = {
  app: [
    {
      name: "digital-platform",
      script: "ts-node",
      args: "./src/server.ts",
      instances: 1,
      autorestart: true,
      watch: ["src"],
      ignore_watch: ["node_modules", "logs", ".git", "public"],
      watch_options: {
        followSymlinks: false,
      },
      env: {
        NODE_ENV: "development",
        PORT: 5020,
        DB_HOST: "localhost",
        DB_USERNAME: "root",
        DB_PASSWORD: "ips12345",
        DB_NAME: "digital_platform",
        JWT_SECRET: "your-local-jwt-secret-key",
        ADMINEMAIL: "admin@example.com",
        ADMINPASS: "your-password",
        FRONTEND_URL: "http://localhost:3000",
        LOG_LEVEL: "debug",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 5020,
        DB_HOST: "192.168.1.23",
        DB_USERNAME: "maceratauniversity",
        DB_PASSWORD: "production-password",
        DB_NAME: "maceratauniversity",
        JWT_SECRET: "your-production-jwt-secret-key",
        ADMINEMAIL: "admin@example.com",
        ADMINPASS: "your-production-password",
        FRONTEND_URL: "http://production-frontend.com",
        LOG_LEVEL: "error",
      },
      error_file: "logs/err.log",
      out_file: "logs/out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      max_memory_restart: "1G",
    },
  ],
};
